- name: Ansible apt module 
  hosts: tmpl
  become: yes
  tasks:
    - name: Ansible apt to install multiple packages -
      register: updatesys
      apt:
        update_cache: yes
        name:
          - htop
          - mc
        state: present
