---
- hosts: tmpl
  tasks:
    - name: install mc
      apt:
        name: mc
        state: present
        
    - name: install mc
      apt:
        name: htop
        state: present

      
        
