- name: Ansible apt module 
  hosts: new_lotus_nodes
  become: yes
  tasks:
    - name: Ansible apt to install multiple packages -
      register: updatesys
      apt:
        update_cache: yes
        name:
          - mc
          - wget
        state: present

    - import_role:
        name: abdennour.golang
      vars:
        golang_version: "1.19.8"
      become: yes
      
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/filecoin-project/lotus.git'
        dest: /root/lotus/lotus
        version: v1.23.0

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /root/scripts/make-ffi-build
        dest: /root/lotus
    
    - name: make-ffi-build
      ansible.builtin.shell:
        cmd: make clean 
        chdir: /root/lotus/lotus
    
    - name: Ansible apt upgrade
      register: updatesys
      apt:
        upgrade: yes

    - debug: var=ps.stdout_lines
