- name: Ansible apt module 
  hosts: new_lotus_nodes
  become: yes
  tasks:
    - name: Ansible apt to install multiple packages -
      register: updatesys
      apt:
        update_cache: yes
        name:
          - mc
          - wget
        state: present

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/filecoin-project/lotus.git'
        dest: /root/lotus
        version: v1.23.0
    
    - name: Ansible apt upgrade
      register: updatesys
      apt:
        upgrade: yes
