- name: Ansible apt module 
  hosts: new_lotus_nodes
  become: yes
  tasks:
    - name: Ansible apt to install multiple packages -
      register: updatesys
      apt:
        update_cache: yes
        name:
          - mc
          - wget
        state: present

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/filecoin-project/lotus.git'
        dest: /root/lotus/lotus
        version: v1.23.0

        # You can also use the 'cmd' parameter instead of free form format.
    - name: make-ffi-build
      ansible.builtin.shell:
        cmd: make clean
        chdir: /root/lotus/lotus
    
    - name: Ansible apt upgrade
      register: updatesys
      apt:
        upgrade: yes
