- name: Ansible apt module 
  hosts: new_lotus_nodes
  become: yes
  tasks:
    - name: Ansible apt to install multiple packages -
      register: updatesys
      apt:
        update_cache: yes
        name:
          - htop
          - mc
          - mesa-opencl-icd 
          - ocl-icd-opencl-dev
          - gcc
          - git
          - bzr
          - jq
          - pkg-config
          - curl 
          - clang
          - build-essential
          - hwloc
          - libhwloc-dev
          - wget
          - aria2
        state: present

    - import_role:
        name: abdennour.golang
      vars:
        golang_version: "1.19.12"
      become: yes
      
    - name: Git checkout lotus
      ansible.builtin.git:
        repo: 'https://github.com/filecoin-project/lotus.git'
        dest: /data/lotus/lotus
        version: v1.23.2

    - name: Git checkout scripts
      ansible.builtin.git:
        repo: 'git@github.com:std/scripts.git'
        dest: /data/lotus/
        
        
    - name: Copy file make-ffi-build
      ansible.builtin.copy:
        src: /root/scripts/
        dest: /data/lotus
         
    
    - name: make-ffi-build
      ansible.builtin.shell:
        cmd: ls -1 #sh make-ffi-build
        chdir: /data/lotus
    
    - name: Ansible apt upgrade
      register: updatesys
      apt:
        upgrade: yes

    - debug: var=ps.stdout_lines
