- name: Ansible apt module 
  hosts: all-lotus
  become: yes
  tasks:
    - name: Ansible apt to install multiple packages -
      register: updatesys
      apt:
        update_cache: yes
        name:
          - prometheus-node-exporter
        state: present
    - name: Ansible apt upgrade
      register: updatesys
      apt:
        upgrade: yes
